import { mkdirSync, writeFileSync } from "node:fs";
import { loadConfig } from "../src/config/index.js";

/**
 * Locked decision #2: vector dimension is config-driven, never hardcoded in the
 * schema. pgvector *indexes* need a fixed dimension, so this script emits the
 * index DDL from EMBEDDING_DIMENSION. Run after `supabase db push`:
 *
 *   pnpm db:vector-index
 *   psql "$DATABASE_URL" -f supabase/generated/vector_index.sql
 */
const cfg = loadConfig();
const sql = `-- generated by scripts/generate-vector-index.ts (EMBEDDING_DIMENSION=${cfg.EMBEDDING_DIMENSION})
-- re-run after changing the embedding model/dimension; existing chunks with a
-- different dimension should be regenerated (see README → "Changing embedding models").
drop index if exists chunk_embedding_hnsw_idx;
alter table chunk
  alter column embedding type vector(${cfg.EMBEDDING_DIMENSION})
  using embedding::vector(${cfg.EMBEDDING_DIMENSION});
create index chunk_embedding_hnsw_idx on chunk
  using hnsw (embedding vector_cosine_ops);
analyze chunk;
`;
mkdirSync("supabase/generated", { recursive: true });
writeFileSync("supabase/generated/vector_index.sql", sql);
console.log(`wrote supabase/generated/vector_index.sql (dimension ${cfg.EMBEDDING_DIMENSION})`);
